# Generated by Django 5.2.6 on 2025-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text="Email backend (e.g., 'django.core.mail.backends.smtp.EmailBackend' for SMTP).", max_length=255)),
                ('email_host', models.CharField(blank=True, help_text="SMTP server host (e.g., 'smtp.gmail.com').", max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='SMTP server port (e.g., 587 for TLS, 465 for SSL).')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS for secure connection (recommended for port 587).')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL for secure connection (enable for port 465, disable for TLS).')),
                ('email_host_user', models.CharField(blank=True, help_text='SMTP server username (e.g., your email address).', max_length=255)),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP server password or app-specific password.', max_length=255)),
                ('default_from_email', models.EmailField(blank=True, help_text="Default sender email address (e.g., 'your-email@example.com').", max_length=254)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterModelOptions(
            name='useremail',
            options={'verbose_name': 'User Email', 'verbose_name_plural': 'User Emails'},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
